name: Build and Push Docker Images

on:
  push:
    branches: [main]
    workflow_dispatch: # For manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_dir: ${{ file('images.txt') }}
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry with access token
        run: |
          echo "$DOCKER_ACCESS_TOKEN" | docker login -u _oauth --password-stdin
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push images
        run: |
          for image_dir in ${{ matrix.image_dir }}; do
            version=$(cat "./$$image_dir/VERSION")
            image_name="corpdk/$$image_dir"
            docker buildx build --push --platform ${{ matrix.platform }} -t "$image_name:$version" -t "$image_name:latest" ./$$image_dir
          done

env:
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
